import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  //refreth() ui
  //router.refresh();
  //for the server side
  // use cache for ppr 
  // react compiler support 
  // updatepath to update the data fetching on the server side
  //support react 19.2
  // support activity feature
  // require node.js 20
  // support node.js 20 features and optimizations
  // updatetag for server actions
  // turbapack is the default bundlier
  // faster builds and hot module replacement (HMR)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
